### ISSUE TITLE
Change the point example

### ISSUE THREAD

**Issue by hgrecco** [andreaferretti/on-rust-and-nim#3]
I think that the point example is a little bit more verbose that it could be.

``` rust
struct Point {
    x: f64,
    y: f64,
}

impl Add for Point {
    type Output = Point;
    fn add(self, other: Point) -> Point {
        Point{x: self.x + other.x, y: self.y + other.y}
    }
}
```

**Comment by andreaferretti** [comment]
Yes, I have already received pull requests for this. I mention them in the first paragraph. I cannot really change the later content, though, since I am reporting what I have written in the mail, and changing it now would only add to confusion
